# Generated by Django 3.2.23 on 2023-11-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(max_length=50, verbose_name='歌名')),
                ('singer', models.CharField(max_length=50, verbose_name='歌手')),
                ('time', models.CharField(max_length=10, verbose_name='时长')),
                ('album', models.CharField(max_length=50, verbose_name='专辑')),
                ('languages', models.CharField(max_length=20, verbose_name='语种')),
                ('type', models.CharField(max_length=20, verbose_name='类型')),
                ('release', models.DateField(verbose_name='发行时间')),
                ('img', models.FileField(upload_to='songImg/', verbose_name='歌曲图片')),
                ('lyrics', models.FileField(blank=True, default='暂无歌词', upload_to='songLyric/', verbose_name='歌词')),
                ('file', models.FileField(upload_to='songFile/', verbose_name='歌曲文件')),
            ],
            options={
                'verbose_name': '歌曲信息',
                'verbose_name_plural': '歌曲信息',
            },
        ),
    ]
