# Generated by Django 3.2.23 on 2023-12-06 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
